[package]
name = "janus-server"
version = "0.0.4"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
libp2p = "0.16.0"
parity-multiaddr = "0.7.0"
futures = "0.3.1"
futures-util = "0.3.1"
async-std = "1.4.0"
sodiumoxide = "0.2.5"
faster-hex = "0.4.1"
config = "0.10.1"

serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"

failure = "0.1.6"
base64 = "0.11.0"
fnv = "1.0.6"
log = "0.4.8"
env_logger = "0.7.1"
void = "1.0.2"
clap = "2.33.0"
exitfailure = "0.5.1"
ctrlc = "3.1.3"
async-tungstenite = "0.3.1"

[dependencies.tungstenite]
version = "0.9.2"
default-features = false

[dev-dependencies]
rand = "0.7.3"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
