[package]
name = "janus_client"
version = "0.0.1"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
janus_server = { path = "../server" }
libp2p = "0.13.1"
parity-multiaddr = "0.6.0"
tokio = "0.1.22"
futures = "0.1.29"

serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"

failure = "0.1.6"
fnv = "1.0.6"
