[package]
name = "utils-wasm"
version = "1.0.0"
edition = "2018"
authors = ["Fluence Labs"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.58"
faster-hex = "0.4.1"
sha3 = "0.8.2"
