[package]
name = "janus-ipfs"
version = "0.0.1"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
janus-libp2p = { path = "../../crates/libp2p" }
janus-client = { path = "../rust-libp2p" }
faas-api = { path = "../../faas-api" }
ctrlc-adapter = { path = "../../crates/ctrlc-adapter"}
libp2p = "0.17.0"
parity-multiaddr = "0.8.0"
multihash ="0.10.0"
async-std = "1.5.0"
futures = "0.3.4"
futures-util = "0.3.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
failure = "0.1.6"
fnv = "1.0.6"
bs58 = "0.3.0"
log = "0.4.8"
env_logger = "0.7.1"
void = "1.0.2"
rand = "0.7.3"
itertools = "0.9.0"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
async-timer = { version = "0.7.3", features = ["stream"] }

[dev-dependencies]
