[package]
name = "janus-client"
version = "0.0.2"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
janus-server = { path = "../../server" }
libp2p = "0.16.1"
parity-multiaddr = "0.7.0"
async-std = "1.4.0"
futures = "0.3.1"
futures-util = "0.3.1"

serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"

failure = "0.1.6"
fnv = "1.0.6"
bs58 = "0.3.0"
log = "0.4.8"
env_logger = "0.7.1"
void = "1.0.2"

itertools = "0.8.2"
bencher = "0.1.5"

[dev-dependencies]
rand = "0.7.3"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
