[package]
name = "janus-client"
version = "0.0.2"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
janus-server = { path = "../../server" }
libp2p = "0.16.2"
parity-multiaddr = "0.7.0"
multihash ="0.10.0"
async-std = "1.5.0"
futures = "0.3.4"
futures-util = "0.3.4"

serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"

failure = "0.1.6"
fnv = "1.0.6"
bs58 = "0.3.0"
log = "0.4.8"
env_logger = "0.7.1"
void = "1.0.2"
rand = "0.7.3"

itertools = "0.9.0"
bencher = "0.1.5"

[dev-dependencies]
rand = "0.7.3"
reqwest = "0.10.4"
tokio = { version = "0.2.13", features = ["full", "macros"] }
