[package]
name = "trust-graph"
version = "0.0.1"
authors = ["Fluence Labs"]
edition = "2018"

[dependencies]
libp2p-core = "0.16.0"
parity-multiaddr = "0.7.0"

serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
bs58 = "0.3.0"

failure = "0.1.6"
base64 = "0.11.0"
log = "0.4.8"
env_logger = "0.7.1"
exitfailure = "0.5.1"

[dev-dependencies]
rand = "0.7.3"

