[package]
name = "trust-graph"
version = "0.0.1"
authors = ["Fluence Labs"]
edition = "2018"
description = "trust graph"
license = "MIT"

[dependencies]
libp2p-core = "0.17.0"
parity-multiaddr = "0.8.0"
serde = { version = "1.0.104", features = ["derive"] }
bs58 = "0.3.0"
failure = "0.1.6"
log = "0.4.8"
itertools = "0.9.0"

[dev-dependencies]
rand = "0.7.3"
